version: "3.9"
services:
  table-extractor:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    restart: always
    build: .
    ports:
      - "8555:8555"
    entrypoint: gunicorn --workers 1 --threads 1 --max-requests 1000 --max-requests-jitter 100 --timeout 600 -b 0.0.0.0:8555 wsgi:application